/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get configuration */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current configuration snapshot for UI */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Update configuration */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfigUpdateRequest"];
                };
            };
            responses: {
                /** @description Configuration persisted and health recalculated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigUpdateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tunnel runtime status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description WireGuard runtime status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keygen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generate a new WireGuard key pair */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Generated key metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KeygenResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh service and VPS health checks now */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Session established */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthOkResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set or rotate UI password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordRequest"];
                };
            };
            responses: {
                /** @description Password configured */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthOkResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pubkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List allowed Ed25519 public keys */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Allowed keys */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthPubkeysResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Add allowed Ed25519 public key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthPubkeyAddRequest"];
                };
            };
            responses: {
                /** @description Key registered */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthPubkeyAddResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pubkeys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete allowed Ed25519 public key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Key deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthOkResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active UI sessions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active sessions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSessionsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke UI session */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session revoked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthOkResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthOkResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get challenge for pubkey auth */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthChallengeRequest"];
                };
            };
            responses: {
                /** @description Challenge generated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthChallengeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify challenge signature and issue session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthVerifyRequest"];
                };
            };
            responses: {
                /** @description Signature accepted and session issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthVerifyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rotate/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare key rotation and generate rollback script */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RotatePrepareRequest"];
                };
            };
            responses: {
                /** @description Rotation plan created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RotatePrepareResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rotate/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm or cancel prepared key rotation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RotateConfirmRequest"];
                };
            };
            responses: {
                /** @description Rotation plan applied or cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RotateConfirmResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rotate/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get prepared rotation plan status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rotation plan status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RotateStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kill-switch/script": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download VPS killswitch script */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Script metadata or plain script */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KillSwitchScriptResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vps/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List VPS targets with health and active target */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description VPS targets and current active target */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VpsTargetsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vps/failover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger automatic failover or force specific target */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["VpsFailoverRequest"];
                };
            };
            responses: {
                /** @description Failover result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VpsFailoverResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vps-setup-script": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generate setup script for selected VPS target */
        get: {
            parameters: {
                query?: {
                    vpsId?: string;
                    withCrowdsec?: "1";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Setup script payload with hash and selected VPS */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VpsSetupScriptResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify audit log hash chain integrity */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Audit chain verification report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditVerifyResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RotatePrepareRequest: {
            nextPrivateKey?: string;
            nextPublicKey?: string;
            nextPresharedKey?: string;
        };
        RotateConfirmRequest: {
            planId: string;
            /** @default true */
            apply: boolean;
        };
        RotatePrepareResponse: {
            ok: boolean;
            planId: string;
            expiresInSec: number;
            nextPublicKey: string;
            nextPublicKeyFingerprint: string;
            script: string;
            scriptSha256: string;
        };
        RotateStatusResponse: {
            id: string;
            createdAt: number;
            expiresAt: number;
            nextPublicKey: string;
            nextPublicKeyFingerprint: string;
            scriptSha256: string;
        };
        RotateConfirmResponse: {
            ok: boolean;
            cancelled?: boolean;
            applied?: boolean;
            nextPublicKey?: string;
            nextPublicKeyFingerprint?: string;
        };
        KillSwitchScriptResponse: {
            script: string;
            sha256: string;
            filename: string;
        };
        VpsTarget: {
            id: string;
            name: string;
            ip: string;
            port: number;
            pubKey?: string;
            enabled: boolean;
            priority: number;
            fingerprint?: string;
            health?: {
                ok?: boolean;
                checked?: boolean;
                checkedAt?: string;
                message?: string;
                latencyMs?: number | null;
                okStreak?: number;
                failStreak?: number;
            };
        };
        VpsTargetsResponse: {
            activeVpsId: string;
            targets: components["schemas"]["VpsTarget"][];
        };
        VpsFailoverRequest: {
            targetId?: string;
        };
        VpsFailoverResponse: {
            ok: boolean;
            switched?: boolean;
            activeVpsId: string;
            policy?: {
                activeFailuresRequired?: number;
                candidateSuccessesRequired?: number;
                cooldownMs?: number;
            };
            next?: {
                id?: string;
                name?: string;
                ip?: string;
            };
        };
        VpsSetupScriptResponse: {
            script: string;
            sha256: string;
            filename: string;
            withCrowdsec: boolean;
            vps: {
                id: string;
                name: string;
                ip: string;
                port: number;
            };
        };
        AuditVerifyResponse: {
            ok: boolean;
            entries: number;
            brokenAt?: number;
            reason?: string;
        };
        ConfigUpdateRequest: {
            vpsIp?: string;
            vpsPort?: number;
            vpsPubKey?: string;
            activeVpsId?: string;
            domain?: string;
            /** Format: email */
            acmeEmail?: string;
            failoverPolicy?: {
                activeFailuresRequired?: number;
                candidateSuccessesRequired?: number;
                cooldownMs?: number;
            };
            privateKey?: string;
            services?: ({
                name?: string;
                subdomain?: string;
                target?: string;
                enabled?: boolean;
            } & {
                [key: string]: unknown;
            })[];
            vpsTargets?: components["schemas"]["VpsTarget"][];
        } & {
            [key: string]: unknown;
        };
        ConfigResponse: {
            vpsIp?: string;
            vpsPort?: number;
            vpsPubKey?: string;
            activeVpsId: string;
            domain?: string;
            acmeEmail?: string;
            failoverPolicy?: {
                activeFailuresRequired?: number;
                candidateSuccessesRequired?: number;
                cooldownMs?: number;
            };
            vpsTargets: components["schemas"]["VpsTarget"][];
            auth: {
                passwordEnabled: boolean;
                sessionCount: number;
            };
            privateKey: string;
            vpsPubKeyFingerprint: string;
            vpsFingerprints: {
                [key: string]: string;
            };
            services?: ({
                name?: string;
                subdomain?: string;
                target?: string;
                enabled?: boolean;
            } & {
                [key: string]: unknown;
            })[];
            serviceHealth?: {
                [key: string]: {
                    ok?: boolean;
                    checked?: boolean;
                    statusCode?: number;
                    message?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        } & {
            [key: string]: unknown;
        };
        ConfigUpdateResponse: {
            ok: boolean;
            serviceHealth: {
                [key: string]: {
                    ok?: boolean;
                    checked?: boolean;
                    statusCode?: number;
                    message?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        KeygenResponse: {
            publicKey: string;
            publicKeyFingerprint: string;
        };
        StatusResponse: {
            connected: boolean;
            raw: string;
            peerCount?: number;
        } & {
            [key: string]: unknown;
        };
        AuthOkResponse: {
            ok: boolean;
        };
        PasswordRequest: {
            password: string;
        };
        LoginRequest: {
            password: string;
        };
        AuthSession: {
            id: string;
            createdAt: number;
            expiresAt: number;
            ip: string;
            source: string;
            current: boolean;
        };
        AuthSessionsResponse: {
            sessions: components["schemas"]["AuthSession"][];
        };
        AuthPubkeyItem: {
            id: string;
            name: string;
            addedAt: number;
        };
        AuthPubkeysResponse: {
            pubkeys: components["schemas"]["AuthPubkeyItem"][];
        };
        AuthPubkeyAddRequest: {
            name: string;
            publicKey: string;
        };
        AuthPubkeyAddResponse: {
            ok: boolean;
            keyId: string;
        };
        AuthChallengeRequest: {
            keyId: string;
        };
        AuthChallengeResponse: {
            challengeId: string;
            nonce: string;
            expiresInSec: number;
        };
        AuthVerifyRequest: {
            challengeId: string;
            signature: string;
        };
        AuthVerifyResponse: {
            ok: boolean;
            sessionToken: string;
            expiresAt: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
